# Generated by Django 2.1.3 on 2018-11-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freeshelf', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='book',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='category',
        ),
        migrations.DeleteModel(
            name='Categories',
        ),
    ]
